apiVersion: v1
kind: Service
metadata:
  name: superset-app
spec:
  type: NodePort
  selector:
    app: superset-app
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30100