apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-app
  template:
    metadata:
      labels:
        app: superset-app
    spec:
      containers:
      - name: superset-app
        image: apache/superset:latest
        ports:
        - containerPort: 8088
          name: web
        env:
        - name: SUPERSET_SECRET_KEY
          value: hellodatazip
        command:
        - "/bin/sh"
        - "-c"
        - |
          pip install clickhouse-connect
          superset db upgrade
          superset fab create-admin \
              --username admin \
              --firstname Superset \
              --lastname Admin \
              --email admin@superset.com \
              --password admin
          superset init
          gunicorn --bind  0.0.0.0:8088 \
              --worker-class gthread \
              --workers 10 \
              --timeout 120 \
              --limit-request-line 0 \
              --limit-request-field_size 0 \
              "superset.app:create_app()"